### ISSUE TITLE
Frisian and Sorb cultures

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1065]
After looking at redstonecobra's commits which had added several new cultures to NWO, I looked for ethnic groups that could be added into NWO. i have found two ethnic groups which could be implemented, Frisians a Germanic ethnic group which is mainly concentrated in the Friesland region of the Netherlands and Sorbs a West Slavic ethnic group that is concentrated in the Saxony region of Germany.

https://en.wikipedia.org/wiki/Frisians
https://en.wikipedia.org/wiki/Sorbs

**Comment by simsulla** [comment]
In general I see a point in adding cultures that are majority in a province or more then 1/3 (else they don't show up on the map), but these less then 1/3 minority pops I don't see any value of in the game.  

Anyhow, if you whant to add them, as I told cobra, stay with the most limited estimated, so don't make them unrealistic large, and make them only rural (farmer, miner). This is because we should be a little bit careful for adding to many pops  as it has negative performance implications on the game. 

If you want to add cultures, there is a white spot on the map - Africa and The Pacific. Recommended to start with countries with good census data on ethnicity.

**Comment by simsulla** [comment]
I.e. so from wiki the number of speakers, Frisianas are 366,000 mil, and Sorbs 60,000.

**Comment by simsulla** [comment]
1.14 is planned for 30/4. We need to decide what we are able to get into that release (by setting 1.14 as milestone).
_In general, I usually try and only have a handful of my own ideas (issues) open, and close of those before opening more._
