### ISSUE TITLE
Coptic Egypt proposal

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1090]
Having thought of how the republic of (provisional government) system works by having a minority in a country as its dominant elites, I think it is possible that a decision for Egypt to have Copts/Christian Arabs if Egypt has a republic of government as Copts make up a sizable portion of the Egyptian population at around 10% although I'm not quite sure whether this percentage is large enough for a new culture change decision for Egypt to be made. Also I'm just wondering is there anything in the mod that represents the decline of religious minorities such as Christians and other religions in the Middle East  due to the rise of Islamism and devastating civil wars that happened in the 20th and 21st centuries..

**Comment by simsulla** [comment]
"provisional government", is a bucket of situation (with special flags) that does not fit under the general government types. Typically is minority rule. And yes Coptic rule in Egypt would be such example, but in order for it to fit in the mod it need to have some realistic scenario to it (don't know if this is the case).

The decline of Christians in the middle east is due to several factors (to my understanding). Demographics dominates, in combination with disproportional emigration. Both factors are in the mod, to some extent limited by what any demographic setting is province confined (which limit the negative effect on Christians). Lebanon in the 50s start out with 50/50 Christian. Today less than 1/3 is Christian. Demographics is the major factor.

**Comment by arandomperson5000** [comment]
I'm not quite sure Coptic rule in Egypt would be entirely realistic however there are several separatist groups that favour an independent country or at least autonomy for the Coptic population of Egypt although it seems like these groups are quite tiny and are normally found in the Coptic diaspora rather than the actual population of them in Egypt. The only realistic way of an Egypt ruled by the Copts within NWO's timeframe I could think of is if Egypt was to build its army mainly made up of Copts and that army would later stage a coup bringing Coptic rule to Egypt in a similar way to how the Alawites led by the Assad family became the dominant elite of Syria.
