### ISSUE TITLE
As Afghanistan I'm getting spammed

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1145]
**mo1264king**
For some reason as Afghanistan Im getting spammed messages at the start about various Iranian-Saudi events. For example it tells me that the kurds are trying to break free even though there are no kurds in afghanistan, and it made me declare war on Kurdistan. There are also various events about yemen and syria and the likes. Any fixes?

**Comment by arandomperson5000** [comment]
This problem is already fixed as the events about the Syrian Civil War, the Iraqi Civil War, the Yemeni Civil War and the cold war between Iran and Saudi Arabia were edited in this [commit ](https://github.com/simsulla/nwomod/commit/07817fcac6a76f578a07d2fb22f644d5ecc3661a) had every instance of the condition fire_only_once in them changed to is_triggered_only

**Comment by simsulla** [comment]
Ok, then I'll close this issue.
