### ISSUE TITLE
Syrian Civil War and Possibilities of the collapse of Syria

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#1158]
I propose to add core provinces for the groups Ahrar al-Sham and Hayat-Tahrir Al-Sham in Syria. (As part of the possibility of Collapse of Syria and Civil War.)
In Aleppo and Hama.

For example like Alawite and Druze states.

Links:
Ahrar al-Sham - https://en.wikipedia.org/wiki/Ahrar_al-Sham
Tahrir al-Sham - https://en.wikipedia.org/wiki/Tahrir_al-Sham

**Comment by simsulla** [comment]
Both Ahrar al-Sham and Hayat-Tahrir Al-Sham are salafi islamist groups (according to the wiki articles given), and as political movement it is represented as salafism, and a theocratic government of Syria, or as ISIS in case of a state break up. 
For Druze and Alawite please provide references that there today are significant support for independent states. Both would be one province cores, and works poorly as a game war mechanics perspective. 

Btw, the Assad regime is dominated by Alawites - they are Syria (depending on government type).

**Comment by samwoodzadrot** [comment]
I understand, but I think it really possible to happen. I don't think that this will happen, but it is possible.
But of course, I understand that this is your vision and mod.

**Comment by arandomperson5000** [comment]
Actually there is a Syrian collapse scenario already in NWO to summarise it currently consists of the Alawite state and Jabal al Durze breaking away from Syria and a massive militancy increase in Syria to represent the chaotic aftermath of a rebel victory in the Syrian Civil in a similar way to how Afghanistan pretty much collapsed into [warlordism](https://en.wikipedia.org/wiki/Afghan_Civil_War_(1992%E2%80%9396)) after the Mujahideen had overthrown Najibullah's government in 1992 following the Soviet withdrawal from Afghanistan in 1989.

As for Ahrar al-Sham and Hayat-Tahrir Al-Sham I won't be adding them as countries as they are pretty much military units rather than any form of government of political party. There is already a unique Islamist flag and several Islamist political parties for the Syrian rebel government.

**Comment by arandomperson5000** [comment]
Closing issue since Jabal al Druze and the Alawite State are already in NWO and that Ahrar al-Sham and Hayat-Tahrir Al-Sham are military units.
