### ISSUE TITLE
Germany not unifiying

### ISSUE THREAD

**Issue by FIM-123** [simsulla/nwomod#1205]
I try to play any country either in germany or elsewhere and germany never seems to unify, I think it is because both east germany and the french occupation zone start as a GP

**Comment by arandomperson5000** [comment]
I think you've accidentally downloaded the WIP 2.00 version of NWO rather than the completed 1.13 version if you were looking for a playable version of the NWO mod. I'm planning to replace the French occupation zone with Rhineland as its essentially Germany with a provisional government and as a puppet of France right now.
