### ISSUE TITLE
Superstates the only nation that transforms into the superstate is the one country doing the descisions

### ISSUE THREAD

**Issue by imortaldragonx** [simsulla/nwomod#396]
Currently, when you complete the transition to a super state only you become that super state for example as the British I did all of the pre-requisites to form the EU except when I formed it just turned me into the EU and nobody else just because the AI were too busy dicking around getting all of the military techs. Only one of the states required to form a superstate should have to do the decisions and the other states should automatically join or get a decision or something like in the German unification ion the vanilla game if I create the common market or common defence or poltical union descisions when I make them the other states that it effects should get a descision and if they reject, then I should be able to get a descision to do something about it

**Comment by simsulla** [comment]
Two things;
1, You expand the Union by "any_neighbor", so the UK is a bit "see-locked" and needs to expand via Gibraltar (Spain). This is probably why you have a problem as the UK.
2. The big superstate is really a "two-way" interaction by-design. Other states will join because they want to not because they are "forced/coerced". So, prepare the prerequisites (sphering) then wait, and put your attention to other parts of the political arena (like preventing other super-states from forming).
Your model is a different one, where you sphere all and then form the union. The pathway here is different. all superstates are growing entities, where members are integrated over time. 
If AI only goes for military tech it sounds like a bug. Please provide as screen shot with distorted AI preferences, so we can fix it and balance the preferences a bit making forming super states easier.

**Comment by imortaldragonx** [comment]
I have sphered Spain and I have no idea what to do next how do I get them to join

**Comment by imortaldragonx** [comment]
I have sphered Spain and I have no idea what to do next how do I get them to join, I thought that creating a superstate would work similar to the way it did in the vanilla game i.e if you sphered them and did the decision they went with you into a superstate and if you did after then you would get a decision to annexe them I mean I followed the wiki for the NWO mod on superstates it explains very clearly how to get you to change to the superstate but it doesn't really elaborate on how to get other nations to join I mean Germany is just sitting there on the defence union stage when I have formed the European Union already with just the UK 

    On Wednesday, 27 April 2016, 19:06, simsulla <notifications@github.com> wrote:
 

 Closed #396.—

**Comment by imortaldragonx** [comment]
Actually, it does say in the wiki that you need a Democracy for the European Union does that mean it has excluded government of the realm because that is what the UK has and Germany has it's government type listed as a Democracy so maybe it is that 

    On Wednesday, 27 April 2016, 19:06, simsulla <notifications@github.com> wrote:
 

 Closed #396.—
