### ISSUE TITLE
Greater Italy

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#492]
Gives wrong core on Montauban. Should be somewhere else.

**Comment by DutchDylan** [comment]
I've had some games in which Italy really early on enacted the 'Greater Italy' decision while it was still in the sphere of the US, and after that Italy started wars against those nations with its cores with the US helping on Italys side. It seems kind of unrealistically for Italy to start a war so soon after WW2 and even for the US to help them in such a war.

Could the decision maybe be restricted so that italy can not enact it early on or when it's in the sphere of a nation like the US, France, the UK or any other democracy? Or atleast give tons of infamy if it wants to enact the decision early on. 

Also while Italy only gets 1 core on Switzerland it annexs half of it since it's in the region of East Switzerland, I would propose editing the regions to look like [the regions in the Concert of Europe mod](http://puu.sh/pZs2p.jpg), in which the regions are split up to represent the Historical French, Italian and German speaking population regions. 

btw why does the greater Italy decision claim Annecy as part of Greater Italy while it is not on [the map from the Wikipedia article](https://en.wikipedia.org/wiki/Italian_irredentism#/media/File:RegioniIrredenteItalia.jpg)? It also seems like from the map that Italy claims Malta.

**Comment by simsulla** [comment]
That is part of #532
