### ISSUE TITLE
Techs and globalization

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#534]
**CentricCracker**
Some countries don't research required techs for further globalization, even if it's one tech away. You end up with some countries that never integrate into larger superstates until very late game. Sometimes, never at all.

**Comment by Liegnitz** [comment]
My solution would be giving the country that forms the superstate a decision to get cores on those states to force them into it. (Restore Order, Aquire Cores).

**Comment by DutchDylan** [comment]
@Liegnitz Would such a decision be possible for democracies (or parliamentary democracies) to make? It seems that such a decision should maybe be restrcited to harsher forms of government.

A posible second solution could be that those nations become your puppets if you're friendly enough with them (through a decision that asks them if they want to further integrate), since puppets gain a research bonus on techs their overlords has could this speed up them joing the superstate?

**Comment by Liegnitz** [comment]
You could also make it similar to the Germany - Luxembourg unification event in vanilla Vic2, so the country that should join simply needs to be in your sphere or a puppet of yours. Of course not all countries should be able to enter, only countries that might be able to enter it according to this wiki-picture:
![superstates and cookies](https://cloud.githubusercontent.com/assets/16386550/16785226/3103197c-488d-11e6-8ef1-e4c93df84252.png)

**Comment by DutchDylan** [comment]
@Liegnitz Well countries straight up joining might not be the best idea, if we compare it to the current situation in Europe, not every country in it can just join the EU. A country must abide by the rules and fulfill various requirements of the EU before it can join it, which in a way is represented by the various decisions ingame a country has to enact before it can join a EU superstate. So it would probably be best if countries could not instantly join a superstate once it has formed but maybe get a discount on the techs to join if they are in their sphere if that woudl be possible, since if a superstate of any union would have formed it would be pushing its memberstates to join hard, but it would still want those memberstates to abide by the rules and fulfill the requirements first.

**Comment by simsulla** [comment]
The base problem reported by CentricCracker is ai tech preference. AI does not research "globalization" techs with prio enough. One idea is to use a "decision" where you promote the union among neighbors, giving that country a modifier that would make the ai more likely to research  "globalization" techs. 
Sphering to form the union is as-is a prerequisite for GP prerequisite superstates.
