### ISSUE TITLE
Culture Group Unification

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#555]
**LukeSky**
5. If Flanders/Wallonia becomes independent, there should be a decision to join the Netherlands/France, respectively. France and the Netherlands could have assimilation bonuses on both of Flanders and Wallonia, since the Flemish speak Dutch and Walloons speak French anyways(Possibly replace Flemish with Dutch and Walloon with French).
**Simsulla**
5. The direction is the other way around. As player of Flanders or Wallonia you will not abolish your nation. As France or Holland you might want to absorb these nations. I.e the decision is for France or Holland. This would be part of a more general "culture group" unification.

**Comment by DutchDylan** [comment]
I would advice to keep Flemish and Walloon as seperate cultures from Dutch and French since they indicate the culture differences between the two groups who speak the same language, if a Netherlands or France could absorb an independent Flanders or Wallonia their culture should be added to the accepted culture list if they are absorbed. 
This is coming from someone that lives near the southern border of the Netherlands if you need any credibility :p 

Also @simsulla since this kinda on the topic of different cultures who speak the same language, had you read my reply on the Benelux issue #473 about Luxembourg and possible crisises? I was talking about a proposal to add an Luxembourgian culture to replace the Geman culture in Luxembourg, this to represent the Luxembourgian cultural and linguistic difference from German.

**Comment by simsulla** [comment]
My thinking is to follow the vanilla Culture Group Unification implementation. Walloon etc would be accepted. Flemish and Walloon will remain separate.

**Comment by DutchDylan** [comment]
Yeah that makes sense. But if ingame a Flanders or Wallonia got independent from Belgium, would that disband Belgium as a country (removing BEL cores) and switch the leftover Belgium to the other country (Wallonia or Flanders)? Because else there might be crisises for the liberation of Belgium if a France owned Wallonia. while Belgium still had cores there.
