### ISSUE TITLE
Greater Syria under the Hashemite 

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#642]
**The Sneaky Top Hat**
This idea suddenly popped into my head and it could be an interesting feature to include in the mod.In 1920 ,the Arab kingdom of Syria proclaimed its independence under a Hashemite monarchy with existed for only about 4 months until the French decided to regain control over Syria. Would be realistic that lets say a Hashemite monarchy like Jordan or Iraq at start could have a decision where they reestablish the Arab kingdom of Syria if one of them conquers Syria. On the subject of Arab nationalism, would it be possible for the Hashemite monarchies including Syria to form a union like Arabia as a potential rival to the United Arab Republic through a decision as having a united Arab state was one of the goals of the Hashemite monarchies during WW1 although it failed when Britain and France colonised the region.Also would it be possible to add a Greater Syria decision as the historical region of Syria used to cover the entire Levant including the modern day states of Lebanon,Palestine,Israel and Jordan.
**simsulla**
There was Hashemite cooperation (Arab Federation) between Jordan and Iraq. It is in the mod. Do you have some reference for real world plans of any of these countrys to reinstate the monarchy in Syria. Abdullah I of Jordan had some ambitions, but don't know if those had any substance.
**The Sneaky Top Hat**
Apart from the Fertile Crescent Plan I couldn't find any sources detailing any evidence that the Hashemites wanted to reinstate the monarchy in Syria other than a proposal made by the prime minister of the Kingdom of Iraq Nuri as-Said to unify the entire fertile crescent during WW2.
Here are some sources which detail the fertile crescent plan
http://www.encyclopedia.com/doc/1G2-3424600960.html
https://en.wikipedia.org/wiki/Fertile_Crescent_Plan[/QUOTE]

**Comment by arandomperson5000** [comment]
I apologise for the very long hiatus on this issue however I can't currently work on the issue right now due to a day long trip I have today. I will try to work on the issue tomorrow, anyways it appears the Fertile Crescent plan had some support in Syria during the 1940s with the People's Party which favoured good relations with the West and the Hashemites while its rival the National Party, the biggest political party in Syria at that time opposed the Fertile Crescent Plan. The best chance for the Fertile Crescent Plan to become reality happened during the coup and brief reign of Colonel Sami Hinnawi in 1949 in which after he deposed Zaim the previous Syrian president with the help of groups like the Arab nationalists, the People's Party and pro Hashemite Druze groups, Hinnawi announced elections that managed to get the People's Party the majority of the seats in parliament. At December of 1949 he announced his plans to join Iraq and Jordan in a Fertile Crescent Union however before he could do that another coup led by Colonel Shishakli ousted him out of opposition to a union of Syria with Jordan and Iraq this was similar to Zaim's Policy towards the Hashemite before he was ousted from power. The Hashemites however were not the only one to propose a Fertile Crescent Union, the Syrian Social Nationalist Party founded in Beirut in 1932 by Antoun Saadeh aims to create a sort of a Irredentist Greater Syria which downs over the entire Fertile Crescent including areas like Cilicia, Cyprus and the Sinai Peninsula based on the borders of ancient empires of the like of Babylon and Assyria rather than the traditional geographic region of Syria/Levant. The SSNP was originally a major political party in Syria however it has slowly declined throughout the late twentieth century becoming a fringe group by the 1980s due to allegations of Fascism and also because of a wide crackdown by its old political rivals the Baathist Party. However it appears the SSNP has made a massive revival in recent years currently having from 6000 to 8000 fighters in the Syrian Civil War, due to the rising religious divides within Syria and the pan Arab idealogy of the Baathist Party becoming seemingly outdated when the idea has mainly died off as a major idealogy since the Arab defeat in the 1967 Six Day War , because of this many Syrians have become disillusioned with these ideas and have turned to the SSNP for its supposely secular and Syrian nationalist idealogy that doesn't care for ethnicity or religion. The SSNP appears to have grown to be the second largest party in government held areas after the Baathist Party, I personally think it's idea of a Greater Syria is completely ridiculous, also many people aren't sure whether the SSNP is right wing or left wing. It appears that the Syrian Baathist Party has a desire to rule over the traditional area of a Greater Syria before it was carved up into British and French spheres of influence during the partition of the Ottoman Empire, the party clearly wants to rule Lebanon as part of Syria judging by its past intervention, historical claims to the area and occupied areas of the country from 1976 to 2005. It appears that very briefly during the 1970 Jordanian Civil War, Syria wanted to help the PLO win the civil war and perhaps occupy Jordan as part of a Greater Syria judging by its intervention into the civil war however this was stopped in the fear that Israel may go to war against Syria if they were to intervene more heavily in Jordan. For the Fertile Crescent plan ingame I would make a decision for Iraq that requires it to have very positive relations with both Syria and Jordan, once this decision is activated it triggers an event in Syria that lets the country to decide whether Jordan should be united with it as the recreated Arab Kingdom of Syria and be a puppet to Iraq like the current Arab Federation decision or not. As for a Baathist dominated Syria with high jingoism it would get a decision that allows it claim all of the Levant from Aqaba in Jordan to Aleppo in Syria at the cost of gaining infamy. For a SSNP dominated Syria I am not quite sure whether to represent its unrealistic vision for its own version of a Greater Syria as its own decision or to simply go with the ordinary greater Syria decision   I described above.

Map of Greater Syria according to the SSNP link
http://geocurrents.info/wp-content/uploads/2011/04/Greater-Syria-Map.jpg

Sources
https://books.google.ie/books?id=J3PsAb1uV94C&pg=PA60&lpg=PA60&dq=greater+syria+hinnawi&source=bl&ots=5qXk7-vneX&sig=IBvCRCpdt_m8AwMNskR-dv9MKsI&hl=en&sa=X&ved=0ahUKEwiJnMvxtfzQAhVrCMAKHY6rD2YQ6AEIGjAA
https://books.google.ie/books?id=MtwXKb7wMyAC&pg=PA36&lpg=PA36&dq=greater+syria+hinnawi&source=bl&ots=HpjBEYjgjQ&sig=_cDvhAS9MiantAY5x_cwOJVxluY&hl=en&sa=X&ved=0ahUKEwiJnMvxtfzQAhVrCMAKHY6rD2YQ6AEIKzAD
https://www.google.ie/url?sa=t&source=web&rct=j&url=http://acuns.org/wp-content/uploads/2013/01/Syria-Paper-1946-1958-for-ACUNS-Conference-Website-12-June-2014.pdf&ved=0ahUKEwiWwLzdtfzQAhVpLMAKHfIBDV0QFggaMAA&usg=AFQjCNHJeNwkH7bu8WI19BjDjDUcHpY8mg&sig2=ODZcn8g0rmTbfmGQXd2wYA
http://mobile.nytimes.com/2005/04/26/international/middleeast/syrian-troops-leave-lebanon-after-29year-occupation.html
https://www.google.ie/url?sa=t&source=web&rct=j&url=http://www.acpr.org.il/publications/books/syria-4-in-1-nisan.pdf&ved=0ahUKEwirhNWTtvzQAhWHJcAKHeKkBWMQFghoMA4&usg=AFQjCNFUSDNRbRwOxcX6EsXbSolqxZHEyw&sig2=vFzjfK-mENZBbT4z0rW52w
http://foreignpolicy.com/2016/03/28/the-eagles-of-the-whirlwind/
http://www.theatlantic.com/magazine/archive/1987/06/behind-the-terror/376326/
http://www.ozy.com/fast-forward/could-a-nazi-party-soon-rule-syria/71156
https://en.m.wikipedia.org/wiki/Syrian_Social_Nationalist_Party
https://www.britannica.com/biography/Said-Hammami#ref779892
http://www.nybooks.com/articles/1990/11/22/asad-and-black-september/
http://news.bbc.co.uk/onthisday/hi/dates/stories/september/17/newsid_4575000/4575159.stm

**Comment by arandomperson5000** [comment]
[NWO.zip](https://github.com/simsulla/nwomod/files/679355/NWO.zip)
Due to time constraints with the Update's release date and hassle with dealing in commits that for whatever reason, I can't revert it, I have created a zip for the Fertile Crescent Plan that is currently up to date with all the files currently present at the main nwomod repository,
