### ISSUE TITLE
Finnish Karelia

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#695]
During the soviet purge of 1937 almost all Finns in the karelia area were either killed or moved. perhaps you can can recreate the greater finland decision to include karelia.

**Comment by simsulla** [comment]
With Karelia you refer to East Karelia. 
1937 and after. 
I found these figures:
**1926**
Russians  153,967  57.2%	
Karelians  100,781 37.4%	
**1939**
Russians  296,529 63.2%
Karelians 108,571 23.2%
So this is due to immigration of Russians.
After the war the Finish (Karelians) population is reduced 
Russians  412,773 62.7%
Karelians  85,473  13.0%
Will make this an enchantment request for a super-greater Finland. As there is already a "Greater Finland".

**Comment by simsulla** [comment]
Actually will extend Greater Finland.
