### ISSUE TITLE
About Ukraine 1992 year

### ISSUE THREAD

**Issue by catcus** [simsulla/nwomod#696]
Ukraine 1992 year
1. Same-sex sexual activity is legal since 1991.
2. After the Euromaidan event socialist ideology strongly loses the support of population by 20-30%.
3. https://en.wikipedia.org/wiki/Budapest_Memorandum_on_Security_Assurances (I understand that this is too hard to complete, but it's just in case...)

**Comment by simsulla** [comment]
1. will correct.
2. What is "socialist"? Party of Regions/ Opposition Bloc?
3. What should the Budapest Memorandum on Security Assurances do in the game?

**Comment by catcus** [comment]
2. Yes, Party of Regions. By the way, Opposition Bloc consists of former Party regions politicians.
3. Budapest Memorandum makes that Ukraine, Belarus, Kazakhstan to accept Non-Proliferation of Nuclear Weapons or ban from developing nuclear weapons, and USA, UK, Russian Federation must guarantee territorial integrity to them.
Violating that Memorandum by developing nuclear weapons gives Ukraine, Belarus, Kazakhstan more infamy than usual, and by annexing any state from Ukraine, Belarus, Kazakhstan or supporting Novorossiya or separatistic state gives troubles with countries-guarantees and much more infamy to country-guarantee, who violates (In reality Russia, as guarantee, violates Memorandum by annexing Crimea).

P.S. Sorry for my bad English and many letters :)

**Comment by simsulla** [comment]
3. Ok on the Budapest Memorandum will consider some event. But for nuclear capability Ukraine, Belarus and Kazakhstan needs to follow the generic path.
1. I am not sure the loss of electoral support for the Opposition bloc (Party of Regions) in the last election reflect a real loss in support, because if you look on the fraction of eligible voters that voted, correlates with previous high support for Party of Regions. This indicates that their voters stayed at home in the last election an did not vote.
