### ISSUE TITLE
Transcaucasian

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#716]
I would love to see this as a country

https://en.wikipedia.org/wiki/Transcaucasian_Socialist_Federative_Soviet_Republic

**Comment by arandomperson5000** [comment]
I would consider this quite unrealistic.Any movement for a united Transcaucasia had died out by 1936 when the Soviet Union decided to split up the Transcaucasian SFSR into the Georgia,Armenia and Azerbaijan SSRs. The first attempt at establishing a united Transcaucasian state was largely a failure with it only lasting from 22 April to 28 May 1918,it only existed for about a month.It collapsed due to infighting within the ethnic groups.The three successor states of the Transcaucasian Federation, Georgia, Armenia and Azerbaijan all waged war with each other bickering over territorial borders while completely ignoring the biggest threat to these three countries the Russian SFSR, Russia managed to swiftly conquer it's former territories in the Caucasus from 1918 to 1921 all while in a civil war.From there it set up the Transcaucasian SFSR as a puppet state. Giving how quickly this union dissolved it's highly unlikely that those three highly nationalistic ethnic groups ever want to reunify into that union. If they did it would be a lot like Yugoslavia but maybe a much more quicker demise considering how just after independence Armenia went into straight out war with Azerbaijan over the Armenian inhabited Nagorno-Karabakh enclave. Even after the Nagorno-Karabakh war there has still been conflict between those two countries the most recent being in 2016. Not to mention that the idea Transcaucasia as a single country was created by the Russian Empire without any regard for ethnic differences, they just suddenly clumped all these ethnic groups together a bit like what the Colonial Powers did in Africa and the Middle East. I also do believe that Transcaucasia also shares a similar status with Khiva and Bukhara as they were territories that were dissolved permanently by the Soviet Union decades before the startdate of this mod therefore it is a highly antiquated historical region that was dismantled decades ago.

https://en.wikipedia.org/wiki/Armenian%E2%80%93Azerbaijani_War
https://en.wikipedia.org/wiki/Georgian%E2%80%93Armenian_War#Bibliography
https://en.wikipedia.org/wiki/Nagorno-Karabakh_War
https://en.wikipedia.org/wiki/Georgian_Civil_War
https://en.wikipedia.org/wiki/Red_Army_invasion_of_Georgia
https://en.wikipedia.org/wiki/Red_Army_invasion_of_Azerbaijan

**Comment by simsulla** [comment]
Agree, on it being unrealistic and a violation of NWO's "[Prime Directive](https://forum.paradoxplaza.com/forum/index.php?threads/new-world-order-mod.823674/)".
