### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#721]
Ever since the new map update i keep getting a crash on adapting history. I deleted the victoria 2 folder in documents and reinstalled the mod to no avail. Is there a way to fix this?

**Comment by arandomperson5000** [comment]
Did you delete the map cache of Victoria 2 in Program Files also did you just delete the map cache in the documents folder or did you delete the entire Victoria folder in documents.

**Comment by Necessarycoot72** [comment]
1 no
2 both (deleted cache but it did not work. then deleted the whole folder still did not work)

**Comment by simsulla** [comment]
Necessarycoot72 are you working with the github master? 
If so, I am sorry, I am working on #709 using a real map projection instead of Vic2 obstructed map. It loads (screen shot below) (clear cache before starting the game). A need to correct the positions.txt in order to play (a lot of work..)
I committed a temporary reversion of the #709, update your clone and it should be possible to work from the master again. (simsulla is embraced by his bad work practice in messing up github head... )

Kerguelen Island and new sea floor
![image](https://cloud.githubusercontent.com/assets/10263809/18622815/f741a9fa-7e34-11e6-93c3-de5930ebc397.png)

**Comment by simsulla** [comment]
Have committed a reversal, now it should be possible to work on the github master again.
