### ISSUE TITLE
Why Spain at 1946 is a republic?

### ISSUE THREAD

**Issue by Sussudio** [simsulla/nwomod#745]
I started playing with Spain in 1946 and I saw that his government is a republic instead of a dictatorship. Will this be corrected in future versions or you can do something to which Spain is a dictatorship as it was historically?

**Comment by simsulla** [comment]
Spain is a bit tricky. Formally Francoist Spain (formally State of Spain) it was a "monarchy" (Kingdom of Spain from 1947 after a referendum). But having it as a Absolute or Parliamentary Democracy (which most other non absolute monarchies are) would not be correct. Maybe a presidential dictatorship is more appropriate, the problem is that the presidential dictatorship use the same flag as the democracy and then Francoist Spain would not have a special flag
![image](https://cloud.githubusercontent.com/assets/10263809/18806553/fac0a5ea-8230-11e6-9908-b5bc7a5b795f.png)
An alternative would be to make Spain a "Republic" (nationalist).
