### ISSUE TITLE
The South is My Country

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#805]
"The South is My Country (O Sul é o Meu País in Portuguese) is a separatist movement that claims the independence of Brazil's South Region, formed by the states of Paraná, Rio Grande do Sul and Santa Catarina."

So what do you? thunk could this be a new country?

source
https://en.wikipedia.org/wiki/The_South_is_My_Country
https://www.youtube.com/watch?v=rnZ1cvQnUTk&t=0s

**Comment by Liegnitz** [comment]
According to a  2007 newspaper the movement has 30.000 members and 300.000 followers, its one of the biggest new separatist movements, so it seems important. The video also suggests that there is a large german speaking majority in Southern Brazil. 
Gotta wait for simsulla to approve :smiley:

**Comment by arandomperson5000** [comment]
Thanks for letting me know how big the movement actually is. I had earlier created an issue to remove Rio Grande Sul cores from the mod however it it only today that I found out the movement is well and alive with an unofficial referendum that was organised this year that had received 617,000 votes cast on October 1, 96 percent of the votes supported independence. Their reasons for supporting independence from Brazil is mainly due to economic issues including getting less than 20 percent of their tax revenue in return from the Brazilian engorgement spending it most on the Northern States. This situation is a bit similar to the Riograndese Republic in the Ragmuffin War in 1836 to 1845 where it's leaders seceded from Brazil mainly due to economic and cultural issues with Rio de Janerio (Former capital of Brazil). There were other movements in Brazil that sought to secede their respective regions from Brazil like the Confederation of the Equator and the Bahia Republic in the 1830s, however most of these revolts were crushed in the 1830s to 1850s by the Brazilian government, the only movement that succeeded was Uruguay, therefore preventing Brazil from going into a violent breakup of the country like Gran Columbia or the Federal Republic of Central America. Therefore it is highly that bRazil will completely breakup in the near future. 
https://www.washingtonpost.com/news/worldviews/wp/2016/10/05/half-a-million-brazilians-want-to-break-away-and-form-a-new-country/
http://www.nytimes.com/1993/05/12/world/santa-cruz-journal-white-flight-in-brazil-secessionist-caldron-boils.html
https://en.wikipedia.org/wiki/Confederation_of_the_Equator
https://en.wikipedia.org/wiki/Pernambucan_Revolt
https://en.wikipedia.org/wiki/Ragamuffin_War
https://en.wikipedia.org/wiki/Cabanagem

**Comment by simsulla** [comment]
Not sure how to do about this. The current movement is to weak to qualify own cores. But there are Brazil game play considerations. Putting this issue in state waiting state.

**Comment by LordLoko** [comment]
In the defense of the new cores. Brazil already has Rio Grande do Sul cores and USA has CSA cores, I think could work

**Comment by simsulla** [comment]
Will rename Rio Gr.. to O Sul, change the flag and add cores to all three southern states.
