### ISSUE TITLE
 french administrative regions

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#899]
**robert1815**
 Some of the french administrative regions should be reworked to better represent the actual regions, like you did for the USA. Some regions only have 2 provinces (like picardie) while other have quite a lot and look like a blob. I have some maps of the administrative regions that you can use for inspiration (of course some of this regions can be merged together if the number is too high) :

in 1948 :
![image](https://cloud.githubusercontent.com/assets/10263809/21962875/a4c3b440-db2f-11e6-8c68-1061af64a900.png)

after 1982 :
![image](https://cloud.githubusercontent.com/assets/10263809/21962876/a8d8a914-db2f-11e6-99c1-ab0bbdea14c8.png)

after 2016 :
![image](https://cloud.githubusercontent.com/assets/10263809/21962878/afaccf7c-db2f-11e6-9d26-51dd06ee4092.png)

**Comment by opportus** [comment]
I'm French, ask me if you need any sort of info.

The provinces ideally should represent French "départements" though the fact that there are many, it could give too many benefits to France as that would give to her more ressources and change the balance?

As far as I know it has been discused since a while to suppress the "departements" among ultra liberal and "mondialiste" parties, but I really doubt this will happen anytime soon, as départements are too representative of french subcultures.

At contrario, we have the "Front National" which is very popular National-Socialist party in France who want to protect french culture and keep département but instead remove the regions system, which would make more sense for economy reasons.

The regions as you seem to know have been redisigned last year, at the EU will.

https://en.wikipedia.org/wiki/Departments_of_France
https://en.wikipedia.org/wiki/Regions_of_France

**Comment by simsulla** [comment]
We will go with the approximate 1948 regions.
