### ISSUE TITLE
Nerchinsk rename Ulan-Ude , Chita rename Nerchinsk

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#901]
https://en.wikipedia.org/wiki/Federal_subjects_of_Russia

![image](https://cloud.githubusercontent.com/assets/24807237/21994160/f826e646-dc26-11e6-8743-d3fd8349fbff.png)

Need more federal subjects of Russia!

**Comment by arandomperson5000** [comment]
To be more precise here is a more accurate map showing just the autonomous regions

![](http://www.maps-of-europe.net/maps/maps-of-russia/map-of-autonomous-areas-in-russia.jpg)

Areas like Karelia don't need their own cores since there is a decision for Finland that allows it to gain cores on the entirety of Karelia. This is done primarily because of gameplay purposes.

**Comment by simsulla** [comment]
Which are you missing, they are all in the mod.

**Comment by samwoodzadrot** [comment]
Krasnoyarsk

**Comment by simsulla** [comment]
Krasnoyarsk is **not** autonomous.

**Comment by arandomperson5000** [comment]
Noticed a couple of errors with the autonomous regions of Russia in the NWO. First of all Buryatiais palced at the wrong province at Chita instead of Nerchinsk, to fix this Nerchinsk would have to renamed Ulan-Ude the cpaital of Buryatia wile Chita would be renamed Nerchinsk. The cores of Buryatia would be transferred to Ulan-Ude and the pops of both provinces will be switched over to each other.

**Comment by samwoodzadrot** [comment]
https://en.wikipedia.org/wiki/Krasnoyarsk_Krai

**Comment by arandomperson5000** [comment]
Made a mistake in the commit in which the contents of the commit are outside of the NWO folder and I don't know to delete them. I will try to fix it though

**Comment by simsulla** [comment]
Good, closing the issue.
